/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nikolai Jonasson (https://sketchfab.com/nikolaijonasson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/female-marble-statue-polished-but-old-41b024813afd49fb827d942219d89b93
title: Female Marble Statue (Polished but old)
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF, useTexture, shaderMaterial } from "@react-three/drei";
import { useFrame, extend, useThree } from "@react-three/fiber";
import VibrantFragment from "../shaders/vibrant/fragment.glsl";
import VibrantVertex from "../shaders/vibrant/vertex.glsl";
import abstractTexture from "/abstract.jpg"
console.log(abstractTexture)
// type GLTFResult = GLTF & {
// 	nodes: {
// 		defaultMaterial: THREE.Mesh;
// 		defaultMaterial_1: THREE.Mesh;
// 	};
// 	materials: {
// 		Eye_brown: THREE.MeshStandardMaterial;
// 		Material_001: THREE.MeshStandardMaterial;
// 	};
// };

const FemaleVibrantShaderMaterial = shaderMaterial(
	{
		uTime: 0,
		lightPos: new THREE.Vector3(),
		abstractTexture: new THREE.TextureLoader().load(abstractTexture),
		cameraPosition: new THREE.Vector3(),
	},
	VibrantVertex,
	VibrantFragment
);
extend({ FemaleVibrantShaderMaterial });

export function FemaleShader(props) {
	
	const camera = useThree((state) => state.camera);
	console.log("camera pos", camera);

	const { nodes, materials } = useGLTF(
		"female_marble_statue_polished_but_old.glb"
	);

	const femaleVibrantShaderMaterialRef = useRef();

		// console.log(femaleVibrantShaderMaterialRef.current)

	useFrame((state, delta) => {
		femaleVibrantShaderMaterialRef.current.uTime += delta;
		femaleVibrantShaderMaterialRef.current.cameraPosition = camera.position;
	});
	
	const {lightPos}  = {...props}

	console.log(lightPos)
	console.log(props)
	return (
		<group
			{...props}
			dispose={null}
		>
			<group
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.93}
				position={[1, 0, 0]}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.defaultMaterial.geometry}
						material={materials.Eye_brown}
					></mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.defaultMaterial_1.geometry}
						// material={materials.Material_001}
					>
						<femaleVibrantShaderMaterial
							ref={femaleVibrantShaderMaterialRef}
							side={THREE.DoubleSide}
							lightPos={lightPos}
							// abstractTexture={abstractTexture}
						/>
					</mesh>
					<mesh
					rotation={[0, 0, 0]}
					position={[0, 0.75, -2]}
				>
					<planeGeometry args={[7, 3.94, 1, 1]} />
					{/* <femaleVibrantShaderMaterial
						ref={femaleVibrantShaderMaterialRef}
						side={THREE.DoubleSide}
						lightPos={lightPos}
					/> */}
					<meshBasicMaterial color="orange" />
				</mesh>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("female_marble_statue_polished_but_old.glb");
