/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nikolai Jonasson (https://sketchfab.com/nikolaijonasson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/female-marble-statue-polished-but-old-41b024813afd49fb827d942219d89b93
title: Female Marble Statue (Polished but old)
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
	nodes: {
		defaultMaterial: THREE.Mesh;
		defaultMaterial_1: THREE.Mesh;
	};
	materials: {
		Eye_brown: THREE.MeshStandardMaterial;
		Material_001: THREE.MeshStandardMaterial;
	};
};

export function FemaleGround(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"female_marble_statue_polished_but_old.glb"
	) as unknown as GLTFResult;


	const [
		womanTextureDiff,
		womanTextureDisp,
		womanTextureRough,
		womanNormalMap,
	] = useTexture([
		"/textures/ground/aerial_rocks_02_diff_1k.jpg",
		"/textures/ground/aerial_rocks_02_disp_1k.png",
		"/textures/ground/aerial_rocks_02_rough_1k.jpg",
		"/textures/ground/aerial_rocks_02_nor_gl_1k.png",
	]);


	const ambient = 2;

	// console.log(womanTextureDiff);

	return (
		<group
			{...props}
			dispose={null}
		>
			<group
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.93}
				position={[1, 0, 0]}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.defaultMaterial.geometry}
						material={materials.Eye_brown}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.defaultMaterial_1.geometry}
						// material={materials.Material_001}
					>
						<meshStandardMaterial
							map={womanTextureDiff}
							roughnessMap={womanTextureRough}
							displacementMap={womanTextureDisp}
							normalMap={womanNormalMap}
							displacementScale={0.03}
							displacementBias={0.01}
							map-repeat={[5, 5]}
							map-wrapS={THREE.RepeatWrapping}
							map-wrapT={THREE.RepeatWrapping}
							displacementMap-wrapS={THREE.RepeatWrapping}
							displacementMap-wrapT={THREE.RepeatWrapping}
							roughnessMap-wrapS={THREE.RepeatWrapping}
							roughnessMap-wrapT={THREE.RepeatWrapping}
							normalMap-wrapS={THREE.RepeatWrapping}
							normalMap-wrapT={THREE.RepeatWrapping}
						/>
					</mesh>
	
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("female_marble_statue_polished_but_old.glb");
