/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jeant_220 (https://sketchfab.com/juanfranciscotorresvicuna)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/male-human-a-pose-ac9555358aa94532863d9d7ee705dd21
title: Male Human A pose
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    bubuaiStandardSurface1SG: THREE.MeshStandardMaterial;
  };
};

export function Male(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/male_human_a_pose.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01} position={[-1, -1, 0 ]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.bubuaiStandardSurface1SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/male_human_a_pose.glb");
