/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jeant_220 (https://sketchfab.com/juanfranciscotorresvicuna)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/male-human-a-pose-ac9555358aa94532863d9d7ee705dd21
title: Male Human A pose
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture, shaderMaterial } from "@react-three/drei";
import { useFrame, extend } from "@react-three/fiber";
import TunnelFragment from "../shaders/tunnel/fragment.glsl";
import TunnelVertex from "../shaders/tunnel/vertex.glsl";

// type GLTFResult = GLTF & {
//   nodes: {
//     Object_2: THREE.Mesh;
//   };
//   materials: {
//     bubuaiStandardSurface1SG: THREE.MeshStandardMaterial;
//   };
// };

const MaleShaderMaterial = shaderMaterial(
	{
		iGlobalTime: 0,
		iChannel0: { type: "t", value: new THREE.Texture() },
		iChannel1: { type: "t", value: new THREE.Texture() },
	},
	TunnelVertex,
	TunnelFragment
);
extend({ MaleShaderMaterial });

console.log(MaleShaderMaterial);

export function MaleShader(props) {
	const { nodes, materials } = useGLTF("/male_human_a_pose.glb");
	const maleShaderMaterialRef = useRef();

	const [ceramicTexture, colourfulWoodTexture] = useTexture([
		"/textures/tiles/VintageRusticCeramicFloor_diffuseOriginal.jpg",
		"/textures/colorfulwood/Colorful_Painted_Wood_Base_Color.jpg",
	]);

	useFrame((state, delta) => {
		maleShaderMaterialRef.current.iGlobalTime += delta;
		// console.log(maleShaderMaterialRef.current.iGlobalTime)
	});

	console.log(ceramicTexture);
	console.log(colourfulWoodTexture);

	return (
		<group
			{...props}
			dispose={null}
		>
			<group
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.01}
				position={[1, -1, 0]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_2.geometry}
					// material={materials.bubuaiStandardSurface1SG}
				>
					<maleShaderMaterial
						ref={maleShaderMaterialRef}
						side={THREE.DoubleSide}
						iChannel0={ceramicTexture}
						iChannel0-wrapS={THREE.RepeatWrapping}
						iChannel0-wrapT={THREE.RepeatWrapping}
						iChannel1={colourfulWoodTexture}
						iChannel1-wrapS={THREE.RepeatWrapping}
						iChannel1-wrapT={THREE.RepeatWrapping}
					/>
				</mesh>
				{/* <mesh
					rotation={[Math.PI / 2, 0, 0]}
					position={[250, 250, 200]}
				>
					<planeGeometry args={[700, 394, 1, 1]} />
					<maleShaderMaterial
						ref={maleShaderMaterialRef}
						side={THREE.DoubleSide}
						iChannel0={ceramicTexture}
						iChannel0-wrapS={THREE.RepeatWrapping}
						iChannel0-wrapT={THREE.RepeatWrapping}
						iChannel1={colourfulWoodTexture}
						iChannel1-wrapS={THREE.RepeatWrapping}
						iChannel1-wrapT={THREE.RepeatWrapping}
					/>
				</mesh> */}
			</group>
		</group>
	);
}

useGLTF.preload("/male_human_a_pose.glb");
